apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: web-api
        image: project.webapi:v1
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: postgres-secret
        - configMapRef:
            name: web-api-secret
        - configMapRef:
            name: jwt-options-secret
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
